name = "petaboo-api"
compatibility_date = "2024-09-23"
account_id = "e7ede1cb0525601a97c71931146a6696"
main = "apps/api/worker-d1.ts"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "petaboo"
database_id = "7de21e56-0d26-4204-8563-a57bca0772b4"

# Workers Logs設定
[observability]
enabled = true